htarget{1} = phased.RadarTarget(...
    'MeanRCS', 0.1,...
    'OperatingFrequency', fc);
htargetplatform{1} = phased.Platform(...
    'InitialPosition',[100; 8; 0],...
    'Velocity', [4; 2; 0]);

% Calculate the range, angle, and speed of the first target
[tgt1_rng,tgt1_ang] = rangeangle(htargetplatform{1}.InitialPosition,...
        hantplatform.InitialPosition);
tgt1_speed = radialspeed(htargetplatform{1}.InitialPosition,...
        htargetplatform{1}.Velocity,hantplatform.InitialPosition);

    
    
    
htarget{2} = phased.RadarTarget(...
    'MeanRCS', 0.05,...
    'OperatingFrequency', fc);

htargetplatform{2} = phased.Platform(...
    'InitialPosition',[120; 50; 0], ...
    'Velocity',[15; 8; 0]);

[tgt2_rng,tgt2_ang] = rangeangle(htargetplatform{2}.InitialPosition,...
        hantplatform.InitialPosition);
tgt2_speed = radialspeed(htargetplatform{2}.InitialPosition,...
        htargetplatform{2}.Velocity,hantplatform.InitialPosition);